
export const IS_LOADING = 'IS_LOADING';

// USER 
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL =  'LOGIN_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGOUT_SUCCESS =  'LOGOUT_SUCCESS';


// PATIENT
export const FETCH_PATIENT_SUCCESS = 'FETCH_PATIENT_SUCCESS';
export const FETCH_PATIENT_FAIL = 'FETCH_PATIENT_FAIL';
export const PATIENT_CREATE = 'PATIENT_CREATE';
export const PATIENT_CREATE_FAIL = 'PATIENT_CREATE_FAIL';
export const FETCH_PATIENT_DETAIL_SUCCESS = 'FETCH_PATIENT_DETAIL_SUCCESS';
export const FETCH_PATIENT_DETAIL_FAIL = 'FETCH_PATIENT_DETAIL_FAIL';


// COMPOUNDER

export const LOGIN_COMPOUNDER_SUCCESS = 'LOGIN_COMPOUNDER_LOGIN';
export const LOGIN_COMPOUNDER_FAIL = 'LOGIN_COMPOUNDER_FAIL';
export const CREATE_COMPOUNDER_SUCCESS = 'CREATE_COMPOUNDER_SUCCESS';
export const CREATE_COMPOUNDER_FAIL = 'CREATE_COMPOUNDER_FAIL';
export const FETCH_COMPOUNDER_DETAIL_SUCCESS = 'FETCH_COMPOUNDER_DETAIL_SUCCESS';
export const FETCH_COMPOUNDER_DETAIL_FAIL = 'FETCH_COMPOUNDER_DETAIL_FAIL';

// Otp

export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS';
export const SEND_OTP_FAIL = 'SEND_OTP_FAIL';


// Fetch Events

export const FETCH_EVENT_SUCCESS = 'FETCH_EVENT_SUCCESS';
export const FETCH_EVENT_FAIL = 'FETCH_EVENT_FAIL';
